apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-demo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 882956824445.dkr.ecr.us-west-2.amazonaws.com/harish-cicd-pipeline:latest
          ports:
            - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - nodePort: 31479
      port: 8080
      targetPort: 80